### PR TITLE
Allow last statistic and any percentile

### LINKED ISSUE #87: Validator: summarize-statistic supports more aggregations
```
[configuration]
   width-units = 2
   height-units = 1
   summarize-period = 1 day
   summarize-statistic = last
```

image

```
summarize-statistic must be one of:
avg;
max;
min;
sum;
count;
percentile_99;
percentile_95;
percentile_90;
percentile_75;
percentile_50;
median
```

However, last is supported. Update widget docs in charts:

```
“percentile ... (number)", “max”, “min”, “avg”, “sum”, “delta”, “counter”, “last”, “first”, “min_value_time”, “max_value_time”, “count”, median.
```

### PR DESCRIPTION
**Pull request by kirmanak**
Fixes #87

### CODE REVIEW

**Comment by rodionos** [comment]
Add tests that raise error in any syntax percentile_number or percentile(number):

a) `percentile(-10)`
b) `percentile_-10`
c) `percentile(120)`
d) `percentile_120`
e) if percentile is not a number

Add tests that allow (no error):

a) `percentile(25.5)`
b) `percentile_255`
c) `percentile(10)`
d) `percentile_10`

It would be great if you could add more tests for percentile arguments.

**Comment by kirmanak** [comment]
@rodionos Excuse me, why should `percentile_120` and `percentile(120)` raise the error?
Please, take a look at [this configuration](https://apps.axibase.com/chartlab/4aab8b1f/9/).

**Comment by rodionos** [comment]
120 is outside of valid range. Invalid percentiles are converted by charts to some arbitrary values show something else: https://apps.axibase.com/chartlab/952fb14d

**Comment by kirmanak** [comment]
@rodionos I still don't understand. `120` is converted to `p12` in my example (`0` is discarded). In your example `150` is converted to `p15`, which is `15.0%`, so it is valid, in my opinion.

**Comment by kirmanak** [comment]
@rodionos Done

**Pull request merged**
