### PR TITLE
Make script = regexp multiline

### LINKED ISSUE #23: Allow one-line script assignment without endscript
screenshot 2018-09-14_16-25-37

### LINKED ISSUE #45: Validator: script error
image

### PR DESCRIPTION
**Pull request by kirmanak**
Fixes #45 
Fixes #23

### CODE REVIEW

**Comment by kirmanak** [comment]
Fixes #23 as well

**Comment by rodionos** [comment]
Do we have any tests in this project? I'm concerned that validation rules have become such that any change or refactoring risks breaking previous rules.

**Comment by kirmanak** [comment]
@rodionos https://github.com/axibase/axibase-charts-vscode/tree/master/server/src/test

**Comment by rodionos** [comment]
Should the change in validator.ts in this PR have a corresponding change in script.test.ts? I only see a change in validator.ts.

**Pull request merged**
