### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kirmanak**

### CODE REVIEW

**Comment by kirmanak** [comment]
@rodionos @VeselovAlex @unrealwork @annstriganova Any requests?

**Comment by annstriganova** [comment]
:+1:

**Comment by unrealwork** [comment]
Please rename to `CONTRIBUTING.md`

**Comment by kirmanak** [comment]
@unrealwork renamed

**Comment by VeselovAlex** [comment]
IMHO it is better to add a note about project structure

**Comment by kirmanak** [comment]
@VeselovAlex done

**Pull request merged**
