### PR TITLE
Add check on widget where a setting is defined

### LINKED ISSUE #42: Validator: parent setting causes error
image

It's a regular widget (box) which doesn't support `parent` setting.

```
  [series]
    display = false
    [tags]
      Disk_Name = *
      Parent = *     
```

### PR DESCRIPTION
**Pull request by kirmanak**
Fixes #42

### CODE REVIEW

**Comment by rodionos** [comment]
Does it mean that no error will be raised in this case?

```
[widget]
  type = box
  [series]
  [tags]
    summarize-period = 1 day
```

**Comment by kirmanak** [comment]
@rodionos No, it does not. I've added a filter, but did not switch the validation off. Please, review test cases described in [`tags.test.ts`](https://github.com/axibase/axibase-charts-vscode/blob/b7ddfd170e6d34a8d66ec91616ed300582c41a49/server/src/test/tags.test.ts), for example [this](https://github.com/axibase/axibase-charts-vscode/blob/b7ddfd170e6d34a8d66ec91616ed300582c41a49/server/src/test/tags.test.ts#L16). They expect a diagnostic.

**Comment by rodionos** [comment]
We used to have a warning that a setting will be sent to ATSD as a tag. Under what conditions will this warning be sent to ATSD after this PR is merged?

BTW, the `Parent` setting is supported in `[node]` section in the graph widget.

**Comment by kirmanak** [comment]
@rodionos 
The warning will be shown **if** the setting is found in the settings list **and** the name of the section is tags or key or keys **and** **either**(or some) of the following conditions is true:
1) The allowed widget for the setting is not defined
2) `type = ...` was not declared (we don't know the name of the widget)
3) The widget where the setting was found is the widget where it is allowed.

**Pull request merged**
