### PR TITLE
Add settings descriptions

### LINKED ISSUE #12: Settings
Add file with setting descriptions. Extract descriptions from https://github.com/axibase/charts

### PR DESCRIPTION
**Pull request by kirmanak**
Resolves #12

### CODE REVIEW

**Comment by kirmanak** [comment]
@rodionos Descriptions from `atsd` and `charts` repositories are added

**Comment by kirmanak** [comment]
@rodionos I've added hover support.
hover

**Comment by kirmanak** [comment]
@rodionos I've added some tests for hover messages

**Comment by rodionos** [comment]
conflict

**Comment by kirmanak** [comment]
@rodionos the conflict is solved

**Pull request merged**
