### PR TITLE
Allow auto and none for interval

### LINKED ISSUE #21: Auto keyword not supported
Find out what parameters accept auto as valid value.
screenshot 2018-09-14_16-16-43

### PR DESCRIPTION
**Pull request by kirmanak**
Fixes #21

### CODE REVIEW

**Comment by rodionos** [comment]
Intervals do not support none and auto. Only period, summarize-period, and group-period supports 'auto'. Add tests to cover all cases.

**Comment by rodionos** [comment]
@kirmanak  - pls fix merge conflicts

**Comment by kirmanak** [comment]
@rodionos Merge conflicts are fixed.
According to [Anna's research](https://github.com/axibase/axibase-charts-vscode/issues/21#issuecomment-422348965) not only these three settings support `auto`, there are more of them.

**Comment by rodionos** [comment]
> no errors with `auto` and `none`

No errors doesn't mean the setting is supported. It could be ignored by charts, but it should not be allowed by validator.

https://apps.axibase.com/chartlab/959ea27d/2/

The validator must raise an error if the setting is invalid or has no effect such as 'garbage', 'none', '-5 minute' etc. in the example above).

**Comment by kirmanak** [comment]
@rodionos she has mentioned [docs](https://github.com/axibase/charts/blob/master/widgets/shared/README.md#series-settings) in order to show that `auto` is listed as a supported value in several settings.

**Comment by rodionos** [comment]
When adding rules in validator, do not rely on docs. Use docs only as a guidance. Perform your **own** investigation and tests when implementing the validator rules, for each setting separately. Add tests with each PR. Our docs are could be of sync with charts actual behavior.

**Comment by rodionos** [comment]
Only `period`, `summarize-period`, `group-period` supports 'auto'. Other interval settings require time and unit.

**Pull request merged**
