### PR TITLE
Ignore script content

### LINKED ISSUE #80: Validator: return expression shows wrong alert
Version: 1.0.5

```
[configuration]
  height-units = 2
  width-units = 2
  
  script
    function sumTag(series, tag, value) {
      var sum = series.reduce(function (res, s) { 
      var diskParent = s.params.key && s.params.key[0].tags.parent[0];
        return res + ( diskParent === tag && value(s.data) || 0); 
      }, 0);
      return sum;
    }
    window.sumTag = sumTag;
  endscript

[widget]
  type = box
```

image

### LINKED ISSUE #81: Validator: var not found
```
[configuration]
  height-units = 1
  width-units = 1

var cmdb = {
"agent1"	: {"Region": "abc"}
}
endvar

script
  cmdb = @{JSON.stringify(cmdb)}
endscript
```

image

### LINKED ISSUE #82: Validator: allow setting window variables
```
[configuration]
  height-units = 5
  width-units = 1

script
  window.numberToDate = function (n) {
     var di = Math.round(n*1)+"";
     return new Date(di.substring(0,4), di.substring(4,6), di.substring(6,8), di.substring(8,10), di.substring(10,12), di.substring(12,14));
  };
endscript
```

image

We use this method to define custom functions.

### LINKED ISSUE #83: Validator: script checks are broken again
Clearly script/endscript validation is shaky - fix and add more test coverage.

```
[configuration]
  height-units = 5
  width-units = 1

[group]
  [widget]
    type = calendar
    timespan = 8 hour
    summarize-period = 5 minute    
    colors = green,  red
    thresholds = 0, 1000, 999999
    legend-position = hidden
    script
  var stylesheet = document.createElement("style");
  stylesheet.innerHTML = ".axi-calendarchart .axi-chart-series rect:not([fill]):not(.tail) {fill:red}";
  document.head.appendChild(stylesheet);     
    function markTail() {
      widget.series
      .filter(function (s) { return s.data.callers.length > 0 })
        .forEach(function (rawSeries, seriesIdx) {
            //
        })
    }
    widget.on("seriesupdate", markTail);
    widget.zoom.on("changed", markTail);  
endscript
    on-series-click = var st = interval.startTime; et = (interval.endTime == null) ? interval.startTime + 60000*5 : interval.endTime;

[group]
  [widget]
	type = console
    script = if (!config.isDialog) consoleWidget = widget
```

image

### PR DESCRIPTION
**Pull request by kirmanak**
Fixes #83

### CODE REVIEW

**Comment by rodionos** [comment]
This just disables **any** validation of the script, but before the change we performed some validation of the script content and it was useful because it captured some errors. Lets keep script validation as before.

**Comment by kirmanak** [comment]
@rodionos No, it does not. As you can see, I've just moved incrementation of a counter. The bug was caused by skipping line `this.currentLineNumber++` inside a script, so script content was passed to the validator.
Script validation is performed in a separate class [`JsDomCaller`](https://github.com/axibase/axibase-charts-vscode/blob/master/server/src/jsDomCaller.ts). It can be enabled in user settings (default is disabled).

**Comment by rodionos** [comment]
I checked the tests, and only saw a test that ignores script content. 
Add separate tests for issues: 
Fixes #80
Fixes #81
Fixes #82
Fixes #83
For example, for #82 - test that existing var raises no error in the script, whereas unknown var does raise an error because var is not found.

**Comment by kirmanak** [comment]
@rodionos It was supposed to be a hot-fix, not a new complex validation. I've removed all `fixes` statements, only #83 is left, test is provided.

**Pull request merged**
