### PR TITLE
Fix unknown variable when list name is concatenated with equals sign

### LINKED ISSUE #134: List is not found when space between name and equals sign is absent
image

### PR DESCRIPTION
**Pull request by kirmanak**
Fixes #134

### CODE REVIEW

**Comment by kirmanak** [comment]
@rodionos Added

**Comment by rodionos** [comment]
Which test verifies that `enabled=       false` will not raise an error (unknown setting error)?

**Comment by rodionos** [comment]
For some reason github removes extra whitespace when rendering backticked text in PR comments: `enabled=\s\s\sfalse`.

**Comment by kirmanak** [comment]
@rodionos because of GitHub I did not understand the idea. Now I've updated the test coverage.

**Comment by rodionos** [comment]
image

I see tests that check that error is raised if the setting has a non-boolean value, but is there a test that checks that the above settings are correct. Namely, in all the cases on the screenshot, we should **NOT** raise an error.

**Comment by kirmanak** [comment]
@rodionos the required test is [added](https://github.com/axibase/axibase-charts-vscode/pull/135/files#diff-f98305d0d46d2ca76f5e2a9036bd54a4R906)

**Pull request merged**
